Fix warnings in OsinfoLoader boolean support
I always build with -O0, which sometimes makes me some warnings. The newly
introduced boolean support in OsinfoLoader triggers some warnings when building with the
default flags:

osinfo_loader.c: In function 'osinfo_loader_boolean':
osinfo_loader.c:200:255: error: return makes integer from pointer without a cast [-Werror]
     g_return_val_if_fail(ctxt != NULL, NULL);
                                                                                                                                                                                                                                                               ^
osinfo_loader.c:201:257: error: return makes integer from pointer without a cast [-Werror]
     g_return_val_if_fail(xpath != NULL, NULL);
                                                                                                                                                                                                                                                                 ^
osinfo_loader.c: In function 'osinfo_loader_entity.isra.8':
osinfo_loader.c:331:48: error: 'value_bool' may be used uninitialized in this function [-Werror=maybe-uninitialized]
                 osinfo_entity_set_param_boolean(entity, keys[i].name, value_bool);