Remove unused python gobject import
Nothing in examples/demo.py uses this import, and having it causes a
runtime error:

Traceback (most recent call last):
  File "examples/demo.py", line 4, in <module>
    from gi.repository import Libosinfo as osinfo;
  File "/usr/lib64/python2.7/site-packages/gi/__init__.py", line 23, in <module>
    from ._gi import _API, Repository
ImportError: could not import gobject (error was: ImportError('When using
gi.repository you must not import static modules like "gobject". Please
change all occurrences of "import gobject" to "from gi.repository import
GObject".',))